### ISSUE TITLE
portals do not persist between server shutdown/startup

### ISSUE THREAD

**Issue by kotoroshinoto** [iChun/IssueTracker-PortalGun#39]
just an oddity i felt deserved reporting.

**Comment by Flexico** [comment]
Yeah, this is mildly annoying. ^^

**Comment by Flexico** [comment]
An interesting thing I noticed thanks to Opis is that when the server restarts and the portals disappear, the chunks where the portals were stay force-loaded until I shoot new portals from the same gun.

Also, my portal spawners seem to get corrupted after a server restart. It only renders as half of a portal spawner, and if I break it nothing drops. (This pretty major I think; does it deserve a separate issue?)

**Comment by gigabit101** [comment]
Iv got the same issue

**Comment by iChun** [comment]
Fixed, get beta-5

**Comment by gigabit101** [comment]
Yay

**Comment by iChun** [comment]
Your fault, Gig.

**Comment by gigabit101** [comment]
My fault you fixed it but I didn't break it

**Comment by iChun** [comment]
Still, something's your fault.

**Comment by gigabit101** [comment]
Fine so what was the problem anyways

**Comment by iChun** [comment]
I set a variable wrong when the tile entity is created. Was supposed to be
null, I put Blocks.air instead.

**Comment by Flexico** [comment]
A problem I thought would be fixed by this patch is that after a server restart, my portal spawners end up with the bottom half missing. If I right-click on them to change the settings, I get kicked from the server, but the game doesn't crash. If I break the remaining part of the spawner, it disappears without dropping anything.

I suspect it may be caused by the same error in code, what with a block being set to null.

**Comment by iChun** [comment]
Flexico, I can't reproduce this, sorry.

**Comment by Flexico** [comment]
Ah -- I tested it again and it only happens when I have a Wireless Receiver (WR-CBE) touching it. I moved the receiver back a block and put some red alloy wire in between and now it works. :\
