### ISSUE TITLE
No Sound

### ISSUE THREAD

**Issue by cpux64** [iChun/IssueTracker-PortalGun#6]
For some reason, sounds will not work on my game. I tried using AudioMod (which was not even shown on mod list in menu) but there was no difference.

Installed mods:
1.Millienaire
2.Minecraft Forge
3.OptiFine
4.AudioMod
5.Too Many Items
6.Portal Gun
7.iChun Utility

**Comment by iChun** [comment]
Are the files being downloaded?

**Comment by cpux64** [comment]
What do you mean? If you mean the mod files, I downloaded everything through Magic Launcher.

**Comment by cpux64** [comment]
Tried both standard and external. Everything else seems to work though. :o

**Comment by iChun** [comment]
I mean is there a folder called "portalgun" in the "resources" folder of wherever your mod is installed.. People still use magic launcher???

**Comment by cpux64** [comment]
Yeah. And for some reason, when I try to download any mod manually (using a compressor) the files would not save. (But every time I try opening something in the program without decompressing, it always shows this warning message that I do not understand.) It might be a problem on the application.

**Comment by iChun** [comment]
I suggest you try something else rather than Magic Launcher. I've heard it's caused many problems before.

**Comment by SztoDwa** [comment]
To start, I have 1.4.7v5 version, from YogCraft.
I also don't have the sounds, but I verified it - they're not downloading. I can even tell you why - the links look like following: 
http://www.creeperrepo.net/direct/ichun/8e0d3e5975f4722a89c9ee3c40a3ed8d/portalgun%5Eresources%5Esound%5Eportalgun%5Eturret%5Edifferent_turret6.ogg
What's the issue? It's not a direct link! It's a download page, so one can at most download the "wait 5 seconds" webpage... guess what? I checked the sounds folder, it's full of 6.6kB ".ogg" files, that after renaming to ".html"... you guessed it - show the "wait 5 seconds" page.
I humbly suggest to introduce one of these four solutions:
1. Tell me to shut up because I have an outdated version,
2. Rewrite the links to files in your code, to use "wget links" featured on this creeper host thingy,
3. Upload resources (I mean all sounds) on another hosting server to avoid inconvenience
4. Temporary fix - throw all files into zip, upload it, and let me-I mean, users-download and unpack it.
PS. Oh, and I'm using linux, and every time a sound is needed (gun equip, gun shot, aerial faithplate launch etc) game freezes.

**Comment by iChun** [comment]
The hash of the links changes each day to prevent hotlinking. Something Creeperhost does.
The resources ARE online for people to download and install.
The freezing... I'm not too sure what's up with that, but I'll see what I can do.

**Comment by cpux64** [comment]
Oh. There are resource files that I need. Well, it does not really matter now because my computer is getting a new hard drive. Well, Well thanks anyway for the help, help iChun.

**Comment by iChun** [comment]
I'll leave this issue open cause it's an open issue and I really need to debug this.

**Comment by perlguy** [comment]
Simple solution:  include all the resource files in main zip file to start with.  Since the main zip AND the resources are all hosted on creeperhost anyway, I don't see how there's any benefit to keeping them separate, especially if it's going to cause all these problems.

If that's not possible, or is not an attractive solution for you, get creeperhost to give you a location to store the res files that doesn't require the ad/redirect page that's getting download instead of the ogg files.  At the very least... try to add some validation to the process, to prevent html files from being saved in the place of the real ogg files.

**Comment by iChun** [comment]
Its NOT a redirect page. It gets direct downloads from CH.

**Comment by cpux64** [comment]
Ok, then what is the URL for the resources?

**Comment by iChun** [comment]
It's refreshed each day, Creeperhost does that to prevent hotlinking. The mod knows where to look for the direct URL.

**Comment by aaronfranke** [comment]
@iChun Where can the files be downloaded manually? I'm playing an old modpack and there are no sounds from the Portal Gun mod. I suspect that the URLs may no longer be functional.

**Comment by iChun** [comment]
I don't think I even know which files these are anymore, I'm afraid. It's
from a very very old version, and I have long dropped support for my mods
from 1.12.2 and earlier.
